server:
  port: 20611
  tomcat:
    threads:
      max: 200 # 设定处理客户请求的线程的最大数目，决定了服务器可以同时响应客户请求的数,默认200
      min-spare: 50 # 初始化线程数,最小空闲线程数,默认是10
    accept-count: 10 # 等待队列长度

# JWT 配置
jwt:
  secret: YourSuperSecretKeyWhichShouldBeLongAndRandomAndStoredSecurely # 密钥
  expiration: 86400000 # Token 过期时间 (毫秒)，例如 86400000 = 24 小时

# 数据库配置；启动时配置数据库资源信息
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/treasure?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 60000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 120000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
  servlet:
    multipart:
      max-file-size: 15MB #上传文件单个大小限制
      max-request-size: 60MB #上传文件总大小限制
      enabled: true #是否开启文件上传功能，默认false

# MyBatis 配置【如需使用记得打开】
mybatis-plus: # 注意这里从 mybatis 改为 mybatis-plus
  mapper-locations: classpath*:/mapper/**/*.xml # 如果使用 XML 文件，指定路径
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开发时方便查看 SQL
  global-config:
    db-config:
      id-type: auto # 全局主键策略

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
